"""Fixed program_id type to Integer

Revision ID: 365c0b27d94b
Revises: 
Create Date: 2025-04-28 11:47:08.087701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365c0b27d94b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_per_second', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kiosk_id', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('total_inserted', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_consumed', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_statistics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_statistics_ended_at'), ['ended_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_statistics_kiosk_id'), ['kiosk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_statistics_session_id'), ['session_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rfid_card_number', sa.String(length=50), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfid_card_number')
    )
    op.create_table('device_programs',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('device_id', 'program_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_programs')
    op.drop_table('users')
    with op.batch_alter_table('session_statistics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_statistics_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_statistics_kiosk_id'))
        batch_op.drop_index(batch_op.f('ix_session_statistics_ended_at'))

    op.drop_table('session_statistics')
    op.drop_table('programs')
    op.drop_table('devices')
    # ### end Alembic commands ###
